[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-robot-stretch4-flying-gripper"
# Versioning follow CalVer (YYYY.MM.DD) for PEP 440 compliance
version = "2026.09.28"
description = "Inverse-kinematics (IK) based gamepad control of the Stretch 4 mobile manipulator's gripper"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=2.0.0",
    "coal==3.0.3",
    "pin==4.1.0",
    "yourdfpy>=0.0.60"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["stretch4_flying_gripper*"]
